---
- name: Ensure Cockpit Is Present
  become: true
  package:
    name: cockpit
    state: present

- name: Ensure Cockpit Composer Packages Are Present
  become: true
  package:
    name: "{{ cockpit_composer_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_composer | bool

- name: Ensure Cockpit Dashboard Packages Are Present
  become: true
  package:
    name: "{{ cockpit_dashboard_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_dashboard | bool

- name: Ensure Cockpit Doc Packages Are Present
  become: true
  package:
    name: "{{ cockpit_doc_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_doc | bool

- name: Ensure Cockpit Docker Packages Are Present
  become: true
  package:
    name: "{{ cockpit_docker_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_docker | bool

- name: Ensure Cockpit Kdump Packages Are Present
  become: true
  package:
    name: "{{ cockpit_kdump_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_kdump | bool

- name: Ensure Cockpit Kubernetes Packages Are Present
  become: true
  package:
    name: "{{ cockpit_kubernetes_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_kubernetes | bool

- name: Ensure Cockpit Machines Packages Are Present
  become: true
  package:
    name: "{{ cockpit_machines_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_machines | bool

- name: Ensure Cockpit Machines Ovirt Packages Are Present
  become: true
  package:
    name: "{{ cockpit_machines_ovirt_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_machines_ovirt | bool

- name: Ensure Cockpit Networkmanager Packages Are Present
  become: true
  package:
    name: "{{ cockpit_networkmanager_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_networkmanager | bool

- name: Ensure Cockpit Packagekit Packages Are Present
  become: true
  package:
    name: "{{ cockpit_packagekit_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_packagekit | bool

- name: Ensure Cockpit PCP Packages Are Present
  become: true
  package:
    name: "{{ cockpit_pcp_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_pcp | bool

- name: Ensure Cockpit Selinux Packages Are Present
  become: true
  package:
    name: "{{ cockpit_selinux_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_selinux | bool

- name: Ensure Cockpit SOSReport Packages Are Present
  become: true
  package:
    name: "{{ cockpit_sosreport_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_sosreport | bool

- name: Ensure Cockpit Storaged Packages Are Present
  become: true
  package:
    name: "{{ cockpit_storaged_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_storaged | bool

- name: Ensure Cockpit Subscriptions Packages Are Present
  become: true
  package:
    name: "{{ cockpit_subscriptions_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_subscriptions | bool

- name: Ensure Cockpit Tests Packages Are Present
  become: true
  package:
    name: "{{ cockpit_tests_packages }}"
    state: present
  notify: Restart Cockpit
  when: cockpit_tests | bool

- name: Ensure Cockpit Is Running and Starts on Boot
  become: true
  systemd:
    name: cockpit.socket
    state: started
    enabled: true
