---
- name: Ensure Cockpit Is Present
  become: true
  package:
    name: cockpit
    state: present

- name: Ensure Cockpit Composer Packages Are Present
  become: true
  package:
    name: "{{ cockpit_composer_packages }}"
    state: present
  when: cockpit_composer

- name: Ensure Cockpit Dashboard Packages Are Present
  become: true
  package:
    name: "{{ cockpit_dashboard_packages }}"
    state: present
  when: cockpit_dashboard

- name: Ensure Cockpit Doc Packages Are Present
  become: true
  package:
    name: "{{ cockpit_doc_packages }}"
    state: present
  when: cockpit_doc

- name: Ensure Cockpit Docker Packages Are Present
  become: true
  package:
    name: "{{ cockpit_docker_packages }}"
    state: present
  when: cockpit_docker

- name: Ensure Cockpit Kdump Packages Are Present
  become: true
  package:
    name: "{{ cockpit_kdump_packages }}"
    state: present
  when: cockpit_kdump

- name: Ensure Cockpit Kubernetes Packages Are Present
  become: true
  package:
    name: "{{ cockpit_kubernetes_packages }}"
    state: present
  when: cockpit_kubernetes

- name: Ensure Cockpit Machines Packages Are Present
  become: true
  package:
    name: "{{ cockpit_machines_packages }}"
    state: present
  when: cockpit_machines

- name: Ensure Cockpit Machines Ovirt Packages Are Present
  become: true
  package:
    name: "{{ cockpit_machines_ovirt_packages }}"
    state: present
  when: cockpit_machines_ovirt

- name: Ensure Cockpit Networkmanager Packages Are Present
  become: true
  package:
    name: "{{ cockpit_networkmanager_packages }}"
    state: present
  when: cockpit_networkmanager

- name: Ensure Cockpit Packagekit Packages Are Present
  become: true
  package:
    name: "{{ cockpit_packagekit_packages }}"
    state: present
  when: cockpit_packagekit

- name: Ensure Cockpit PCP Packages Are Present
  become: true
  package:
    name: "{{ cockpit_pcp_packages }}"
    state: present
  when: cockpit_pcp

- name: Ensure Cockpit Selinux Packages Are Present
  become: true
  package:
    name: "{{ cockpit_selinux_packages }}"
    state: present
  when: cockpit_selinux

- name: Ensure Cockpit SOSReport Packages Are Present
  become: true
  package:
    name: "{{ cockpit_sosreport_packages }}"
    state: present
  when: cockpit_sosreport

- name: Ensure Cockpit Storaged Packages Are Present
  become: true
  package:
    name: "{{ cockpit_storaged_packages }}"
    state: present
  when: cockpit_storaged

- name: Ensure Cockpit Subscriptions Packages Are Present
  become: true
  package:
    name: "{{ cockpit_subscriptions_packages }}"
    state: present
  when: cockpit_subscriptions

- name: Ensure Cockpit Tests Packages Are Present
  become: true
  package:
    name: "{{ cockpit_tests_packages }}"
    state: present
  when: cockpit_tests

- name: Ensure Cockpit Is Running and Starts on Boot
  become: true
  systemd:
    name: cockpit
    state: restarted
    enabled: true
